### ISSUE TITLE
Issue importing JSON using script

### ISSUE THREAD

**Issue by Nosphorus** [mattfield11/mqtt-elasticSearch#1]
Hi, I followed your tutorial on Smart Factory, however I can't get the dataString to divide the fields into individual fields.

Example payload:
```
 {
"device":"368640",
"deviceType":"Sigfox-Tracker",
"version":3,
"time":"Tue Aug 21 2018 02:33:05 GMT+0000 (UTC)",
"rssi":"-120.00",
"battery":3.28,
"temp":20.87,
"soil":1915,
"xAxis":59,
"yAxis":-38,
"zAxis":994
}
```

![untitled-1](https://user-images.githubusercontent.com/10903193/44418609-c3851880-a570-11e8-99ff-f4d3d57536df.jpg)

Here is the data visualised in Kibana. The topmost is using your scrip, and the second is if I manually add data to make the mapping for the index. Any help would be greatly appreciated.

**Comment by mattfield11** [comment]
You would need to either use an ingest pipeline (see the elasticsearch
docs) or modify the python script to parse out the json directly.

**Comment by Nosphorus** [comment]
I managed to correct it after modifying the script and adding an ingest pipeline. Had to change the date back to epoch for Kibana to recognise it as a timestamp. Thank you for the script though Matt, I wouldn't of made it this far without you.

**Comment by mattfield11** [comment]
Great .glad you could get it working!
